### ISSUE TITLE
Script not being rendered.

### ISSUE THREAD

**Issue by blairpanek** [artf/grapesjs-custom-code#2]
I have read the message when trying to implement script onto the canvas. I was just wondering why you prevent it?

**Comment by artf** [comment]
Because what is done by the script inside a custom code can't be controlled (eg. the script has access to the whole document node so it can also break the editor, even involuntary). So, for example, let's say your script it's a widget which creates a `<button>` element, that button is created outside the editor context, therefore is not connected, so you can't select/edit it, this can cause a lot of confusion for the one who uses the editor

**Comment by Andrew-Chen-Wang** [comment]
A solution to this might be to use the native (I think) functionality of displaying the final HTML/CSS and instead have a new JS portion only be editable (I'm not sure if not letting users edit the HTML was part of the decision in not letting the source code display be editable). When you display the modal for the source code, this is where you can 1. define external script tags like importing jquery/fontawesome or 2. defining inline script tags which is what's in question.

That ignores the "you can't select/edit it" issue. The next issue is: "button is created outside the editor context." I just found this awesome library today! But that means I'm totally new to the code. I'm quite unfamiliar with how you're initially loading the canvas's iframe. Are you just setting the iframe's srcdoc to your custom HTML code? If so, I don't exactly see a problem with saving a user's inline JS in memory then inputting it when updating the iframe.
